[project]
name = "mcp-tools"
version = "0.1.0"
description = "LLM MCP Tools"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "fastmcp>=2.10.6",
    "psutil>=7.0.0",
    "pytz>=2025.2",
]
